name: CICD
on:
  workflow_dispatch: 

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: write code
        run: echo "writing the code"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build using docker
        run: echo "building docker image"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "testing code"
        
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "deploying code"
        
    
