name: trying matrix
on:
  workflow_dispatch: 
jobs:
  naming:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
        
    runs-on: ${{matrix.os}}-latest
    steps:
      - name: cheking os
        run: echo "running ${{matrix.os}}"
