name: checking scheduling
on:
  schedule:
    - cron: "30 17 * * *"

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello! It's 10:44 PM IST."

      - name: Show Date
        run: date
